[package]
name = "ed-colonization"
version = "0.1.0"
edition = "2024"

[dependencies]
cross-xdg = "2.0.0"
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
regex = "1.12.2"
